<?php
/**
 * @link      https://github.com/oakensoul/application-skeleton for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr.
 * @license   http://opensource.org/licenses/BSD-2-Clause BSD-2-Clause
 * @package   application-skeleton
 */

?>

<div class="container theme-docs-container">
  <div class="row">
    <div class="col-md-3">

    <div class="panel panel-default side-nav">
  <!-- Default panel contents -->
  <div class="panel-heading">    <h3 class="panel-title">Panel title</h3>
  </div>

  <!-- List group -->
  <div class="list-group">
  <a href="#one" class="list-group-item active">
    Section One
  </a>
  <a href="#two" class="list-group-item">Section One</a>
  <a href="#three" class="list-group-item">Section Two</a>
  <a href="#four" class="list-group-item">Section Three</a>
  <a href="#five" class="list-group-item">Section Four</a>
</div>
</div>

<div class="panel panel-default side-nav">
  <!-- Default panel contents -->
  <div class="panel-heading">    <h3 class="panel-title">Powered By</h3>
  </div>
  <div class="panel-body">
  <ul class="nav nav-pills nav-stacked">
    <li>
      <a href="http://framework.zend.com/" class="list-group-item" style="background-color: #0091d5; color: white;">
      <img src="/theme/oakensoul/img/zend-framework-2.png" width="173" height="41" alt="Zend Framework 2">
    </a></li>

    <li><h4><a href="http://getbootstrap.com/" class="list-group-item" style="background-color: #563d7c; color: white; line-height: 41px;">Twitter Bootstrap 3</a></h4></li>

    <li>
      <a href="http://jquery.com/" class="list-group-item" style="background-color: #0769AD; color: white;">
      <img src="/theme/oakensoul/img/jquery.png" width="173" height="41" alt="jQuery">
    </a></li>

    <li><h4><a href="http://cornerstone.oakensoul.com/" class="list-group-item" style="background-color: #5a4c3f; color: white; line-height: 41px;">Cornerstone</a></h4></li>
  </ul>

  </div>
  </div>

    </div>



    <div class="col-md-9">
      <?php echo $this->partial('layout/partials/page-header'); ?>

      <section class="theme-docs-section">
          <div class="page-header"><h1 id="one">Section 1</h1></div>
          <p class="lead">"To replace the controller or this view, use the service manager / dependency injection. I'll add documented details soon."</p>
      </section>
      <section class="theme-docs-section">
          <div class="page-header"><h1 id="two" >Section 2</h1></div>
          <p class="lead">Hopefully i'll also add in some extra themes, layouts as well.</p>
      </section>
      <section class="theme-docs-section">
          <div class="page-header"><h1 id="three" >Section 3</h1></div>
          <p class="lead">More documentation to go here..</p>
      </section>
      <section class="theme-docs-section">
          <div class="page-header"><h1 id="four" >Section 4</h1></div>
          <p class="lead">More documentation to go here..</p>
      </section>
      <section class="theme-docs-section">
          <div class="page-header"><h1 id="five" >Section 5</h1></div>
          <p class="lead">More documentation to go here..</p>
      </section>
    </div>
  </div>
</div>

