<?php
/**
 *
 * @author    Oakensoul (http://www.oakensoul.com/)
 * @link      https://github.com/web-masons/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013, github.com/web-masons Contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache-2.0-Clause
 * @package   Cornerstone
 */

?>

<div class="container">

    <div class="blog-header">
        <h1 class="blog-title">Getting Started with Cornerstone</h1>
        <p class="lead blog-description">A ZF2 Application Blueprint for building new PHP web apps using Cornerstone</p>
    </div>

    <div class="row">

        <div class="col-sm-8 blog-main">

            <div class="blog-post">
                <h2 class="blog-post-title">Welcome!</h2>
                <p class="blog-post-meta">September 1, 2014 by <a href="http://github.com/oakensoul/">Oakensoul</a></p>

                <p>If you're seeing this, you've either installed <a href="https://github.com/web-masons/Cornerstone/">Cornerstone</a> or created a new project using our <a href="https://github.com/web-masons/application-blueprint">Application Blueprint</a>, Welcome! You've managed to get through installation, now it's time to get down to the fun part, building stuff.</p>
                <p>A handful of us have decided to create our own GitHub organization and place a collection of our various code projects into it, thus <a href="https://github.com/web-masons/">https://github.com/web-masons/</a> was born.</p>
                <p>If you need assistance, please file an Issue to the project and we'll get back to you as soon as we can. If you're not sure which project to file it under, just file it under the Cornerstone project.</p>
            </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="sidebar-module">
                <h4>GitHub</h4>
                <ol class="list-unstyled">
                    <li><a href="https://github.com/web-masons/">Web Masons</a></li>
                </ol>
            </div>
        </div><!-- /.blog-sidebar -->

    </div><!-- /.row -->

</div>
