<?php
/**
 *
 * @author Oakensoul (http://www.oakensoul.com/)
 * @link https://github.com/oakensoul/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr.
 * @license http://opensource.org/licenses/BSD-2-Clause BSD-2-Clause
 * @package Cornerstone
 */
echo $this->partial('layout/partials/page/header');
?>

<div class="container" id='page-content'>
<?php echo $this->content; ?>
</div>

<?php echo $this->partial('layout/partials/page/footer'); ?>