<?php
/**
 *
 * @author    Oakensoul (http://www.oakensoul.com/)
 * @link      https://github.com/web-masons/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013, github.com/web-masons Contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache-2.0-Clause
 * @package   Cornerstone
 */
echo $this->partial('layout/partials/page/header');
?>

<div class="container" id='page-content'>
<?php echo $this->content; ?>
</div>

<?php echo $this->partial('layout/partials/page/footer'); ?>
