<?php
/**
 *
 * @author WB Games | Turbine
 * @copyright 2013
 * @license All Rights Reserved
 */

// Over ride this per project to setup project specific stuff
// $this->headTitle($this->translate('Mogwai Skeleton Application'));
// $this->headTitle()->setSeparator(' : ');
// $this->headTitle()->setAutoEscape(false);

// $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
// $this->headMeta()->setCharset("utf-8");



