<script id="google-analytics" type="text/javascript">
(function(i,s,o,g,r,a,m) {
  i['GoogleAnalyticsObject']=r;i[r]=i[r] || function() {
    (i[r].q=i[r].q||[]).push(arguments)
    },
  i[r].l=1*new Date();
  a=s.createElement(o), m=s.getElementsByTagName(o)[0];
  a.async=1; a.src=g; m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', '<?php echo $this->mPropertyId; ?>', '<?php echo $this->mDomain; ?>');
<?php if ($this->mTriggerPageView === true) :?>
ga('send', 'pageview');
<?php endif; ?>
</script>