<?php
/**
 *
 * @author Oakensoul (http://www.oakensoul.com/)
 * @link https://github.com/oakensoul/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr.
 * @license http://opensource.org/licenses/BSD-2-Clause BSD-2-Clause
 * @package Cornerstone
 */
?>
          <ul class="nav navbar-nav">
<?php foreach ($this->container as $page): ?>
<?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
            <li class="active"><a href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a></li>
<?php endforeach; ?>
          </ul>
