<?php
/**
 *
 * @author Oakensoul (http://www.oakensoul.com/)
 * @link https://github.com/oakensoul/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr.
 * @license http://opensource.org/licenses/BSD-2-Clause BSD-2-Clause
 * @package Cornerstone
 */
?>
    <ul class="nav navbar-nav">
<?php foreach ($this->container as $page): ?>
<?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>

<?php if( ! $page->hasPages() ): ?>
    <li class="active"><a href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a></li>
<?php else: ?>
    <li>
      <a class="nav-header" href="<?php echo $page->getHref() ?>" data-toggle="dropdown">
        <?php echo $this->translate($page->getLabel()) ?><b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
<?php foreach($page->getPages() as $child): ?>
<?php // when using partials we need to manually check for ACL conditions ?>
<?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
        <li><a href="<?php echo $child->getHref() ?>"><?php echo $this->translate($child->getLabel()) ?></a></li>
<?php endforeach ?>
      </ul>
<?php endif ?>

<?php endforeach; ?>
    </ul>
