<?php
/**
 *
 * @author    Oakensoul (http://www.oakensoul.com/)
 * @link      https://github.com/web-masons/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013, github.com/web-masons Contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache-2.0-Clause
 * @package   Cornerstone
 */
?>
    <ul class="nav navbar-nav">
<?php foreach ($this->container as $page): ?>
<?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>

<?php if( ! $page->hasPages() ): ?>
    <li class="active"><a href="<?php echo $page->getHref() ?>"<?php if ( $page->isActive() ) : ?> class="active"<?php endif; ?>><?php echo $this->translate($page->getLabel()) ?></a></li>
<?php else: ?>
    <li>
      <a class="nav-header" href="<?php echo $page->getHref() ?>"<?php if ( $page->isActive() ) : ?> class="active"<?php endif; ?> data-toggle="dropdown">
        <?php echo $this->translate($page->getLabel()) ?><b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
<?php foreach($page->getPages() as $child): ?>
<?php // when using partials we need to manually check for ACL conditions ?>
<?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
        <li><a href="<?php echo $child->getHref() ?>"<?php if ( $child->isActive() ) : ?> class="active"<?php endif; ?>><?php echo $this->translate($child->getLabel()) ?></a></li>
<?php endforeach ?>
      </ul>
<?php endif ?>

<?php endforeach; ?>
    </ul>
