<?php
/**
 *
 * @author Oakensoul (http://www.oakensoul.com/)
 * @link https://github.com/oakensoul/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr.
 * @license http://opensource.org/licenses/BSD-2-Clause BSD-2-Clause
 * @package Cornerstone
 */
?>

<div class="page-title-container row-fluid">
	<h1 class="page-title"><?php echo $this->title; ?></h1>
	<div id="breadcrumbs">
	  <?php echo $this->navigation('Site\Navigation')->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" &raquo;"); ?>
	</div>
</div>