<footer class="theme-footer">
		<div class="container">
			<p>
				&copy; <?php echo date('Y'); ?> <a href="http://twitter.com/oakensoul" target="_blank">@oakensoul</a>.
			</p>
			<p>
				Code licensed under <a href="http://opensource.org/licenses/BSD-2-Clause" target="_blank">BSD-2-Clause</a>.
			</p>
			<ul class="footer-links">
				<li><a href="//github.com/oakensoul/Cornerstone/tree/master/doc">Cornerstone docs</a></li>
				<li class="muted">·</li>
				<li><a href="//blog.getbootstrap.com">Blog</a></li>
				<li class="muted">·</li>
				<li><a href="https://github.com/oakensoul/Cornerstone/issues?state=open">Issues</a></li>
				<li class="muted">·</li>
				<li><a href="https://github.com/oakensoul/Cornerstone/releases">Releases</a></li>
			</ul>
		</div>
	</footer>