<?php
/**
 *
 * @author    Oakensoul (http://www.oakensoul.com/)
 * @link      https://github.com/web-masons/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013, github.com/web-masons Contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache-2.0-Clause
 * @package   Cornerstone
 */

$this->headTitle()->setSeparator(' : ');
$this->headTitle()->setAutoEscape(false);

$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
$this->headMeta()->setCharset("utf-8");

// I'm still not 100% sold that I even want to keep the theme system. I think I do, just for
// ease of implementing things like site wrap take-overs but i'm just not sure.

$link = array();
$link['rel'] = 'stylesheet';
$link['type'] = 'text/css';
$link['media'] = 'screen';
$link['href'] = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css';
$this->headLink($link, 'APPEND');

$link['href'] = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css';
$this->headLink($link, 'APPEND');

$this->inlinescript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js', 'text/javascript');
$this->inlinescript()->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js', 'text/javascript');
