<?php
/**
 *
 * @author    Oakensoul (http://www.oakensoul.com/)
 * @link      https://github.com/web-masons/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013, github.com/web-masons Contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache-2.0-Clause
 * @package   Cornerstone
 */

$this->headTitle()->setSeparator(' : ');
$this->headTitle()->setAutoEscape(false);

$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
$this->headMeta()->setCharset("utf-8");

$link = array();
$link['rel'] = 'stylesheet';
$link['href'] = '/theme/default/css/main.css';
$link['type'] = 'text/css';
$link['media'] = 'screen';
$this->headLink($link, 'APPEND');

$link = array();
$link['rel'] = 'shortcut icon';
$link['href'] = '/theme/default/img/favicon.png';
$this->headLink($link, 'APPEND');
