<?php
/**
 *
 * @author Oakensoul (http://www.oakensoul.com/)
 * @link https://github.com/oakensoul/Cornerstone for the canonical source repository
 * @copyright Copyright (c) 2013 Robert Gunnar Johnson Jr.
 * @license http://opensource.org/licenses/BSD-2-Clause BSD-2-Clause
 * @package Cornerstone
 */
$this->headTitle($this->translate('Cornerstone Module'), 'APPEND');
$this->headTitle($this->translate('Oakensoul'), 'APPEND');

echo $this->doctype();
?>

<!--[if lt IE 7]> <html lang="<?php echo Locale::getDefault(); ?>" class="no-js ie lt-ie10 lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html lang="<?php echo Locale::getDefault(); ?>" class="no-js ie lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html lang="<?php echo Locale::getDefault(); ?>" class="no-js ie lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]>    <html lang="<?php echo Locale::getDefault(); ?>" class="ie lt-ie10"> <![endif]-->
<!--[if IE 10]>   <html lang="<?php echo Locale::getDefault(); ?>" class="ie"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="<?php echo Locale::getDefault(); ?>">
<!--<![endif]-->

<head>
<?php echo $this->headTitle() . "\n\n"; ?>
<?php echo $this->headMeta() . "\n\n"; ?>
<?php echo $this->headLink() . "\n\n"; ?>
<?php echo $this->headScript() . "\n\n"; ?>
</head>

<body>
<?php echo $this->partial( 'layout/partials/site-header' ); ?>

<?php echo $this->partial( 'layout/partials/page-content' ); ?>

<?php echo $this->partial( 'layout/partials/site-footer' ); ?>

<?php echo $this->inlinescript(); ?>
</body>
</html>