<?php


// NYI


?>
<div class="span9 nav-collapse">
  <ul class="navmenu header-nav">
<?php $count = 0 ?>
<?php foreach ($this->container as $page): ?>
<?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
<?php // when using partials we need to manually check for ACL conditions ?>
<?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
<?php $hasChildren = $page->hasPages() ?>
<?php if( ! $hasChildren): ?>
    <li><a class="active" href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a></li>
<?php else: ?>
    <li>
      <a class="nav-header" href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?><b class="caret"></b></a>
      <ul class="dropdown-menu" id="page_<?php echo $count ?>">
<?php foreach($page->getPages() as $child): ?>
<?php // when using partials we need to manually check for ACL conditions ?>
<?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
        <li><a href="<?php echo $child->getHref() ?>"><?php echo $this->translate($child->getLabel()) ?></a></li>
<?php endforeach ?>
      </ul>
    </li>
<?php endif ?>
<?php $count++ ?>
<?php endforeach ?>
  </ul>
</div><!--/.nav-collapse -->
